//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class additionalInformationByContact
    {
        public int adCnt_id { get; set; }
        public Nullable<int> cnt_id { get; set; }
        public Nullable<int> kob_id { get; set; }
        public Nullable<int> rgl_id { get; set; }
        public Nullable<int> cne_id { get; set; }
        public Nullable<int> sgm_id { get; set; }
        public Nullable<int> znl_id { get; set; }
        public Nullable<int> rv_id { get; set; }
        public Nullable<int> rm_id { get; set; }
        public Nullable<int> vp_id { get; set; }
        public Nullable<int> cs_id { get; set; }
        public Nullable<int> vvpp_id { get; set; }
    
        public virtual CNE CNE { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual CashSpecialist CashSpecialist { get; set; }
        public virtual KindOfBanking KindOfBanking { get; set; }
        public virtual Regional Regional { get; set; }
        public virtual RegionalsMain RegionalsMain { get; set; }
        public virtual RegionalsVice RegionalsVice { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual VicePresident VicePresident { get; set; }
        public virtual Zonal Zonal { get; set; }
        public virtual VP VP { get; set; }
    }
}
