//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class logins
    {
        public int log_id { get; set; }
        public string usu_document { get; set; }
        public string log_userName { get; set; }
        public string log_password { get; set; }
        public Nullable<bool> log_state { get; set; }
    
        public virtual users users { get; set; }
    }
}
