//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationalInformationByRequest
    {
        public int oibr_id { get; set; }
        public Nullable<int> rqt_id { get; set; }
        public Nullable<short> oibr_deliveredVehicles { get; set; }
        public Nullable<long> oibr_deliveredAmmount { get; set; }
        public Nullable<System.DateTime> oibr_legalizationDate { get; set; }
        public Nullable<System.DateTime> oibr_deliveredDate { get; set; }
        public Nullable<bool> oibr_state { get; set; }
        public Nullable<System.DateTime> oibr_dateUpdateRow { get; set; }
        public string usu_document { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual users users { get; set; }
    }
}
