//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreClient()
        {
            this.PreRequest = new HashSet<PreRequest>();
        }
    
        public int preCli_id { get; set; }
        public string preCli_document { get; set; }
        public Nullable<int> kod_id { get; set; }
        public string preCli_name { get; set; }
        public string preCli_lastName { get; set; }
        public string preCli_phone { get; set; }
        public string preCli_cellPhone { get; set; }
        public string preCli_email { get; set; }
        public Nullable<int> cty_id { get; set; }
        public Nullable<bool> preCli_state { get; set; }
        public Nullable<System.DateTime> preCli_registrationDate { get; set; }
        public string usu_document { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual kindOfDocument kindOfDocument { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest> PreRequest { get; set; }
    }
}
