//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreRequest_Observation
    {
        public int prObs_id { get; set; }
        public int preReq_id { get; set; }
        public string prObs_observation { get; set; }
        public Nullable<System.DateTime> prObs_registrationDate { get; set; }
        public string usu_document { get; set; }
    
        public virtual PreRequest PreRequest { get; set; }
        public virtual users users { get; set; }
    }
}
