//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreRequest()
        {
            this.PreRequest_Observation = new HashSet<PreRequest_Observation>();
        }
    
        public int preReq_id { get; set; }
        public Nullable<System.DateTime> preReq_registrationDate { get; set; }
        public Nullable<int> preCli_id { get; set; }
        public Nullable<int> vehMdl_id { get; set; }
        public Nullable<int> sta_id { get; set; }
        public Nullable<bool> preReq_state { get; set; }
        public string usu_document { get; set; }
        public Nullable<int> firstCanal_id { get; set; }
        public Nullable<int> secondCanal_id { get; set; }
    
        public virtual PreClient PreClient { get; set; }
        public virtual states states { get; set; }
        public virtual users users { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual Canal Canal { get; set; }
        public virtual Canal Canal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest_Observation> PreRequest_Observation { get; set; }
    }
}
