//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.operationalInformationByRequest = new HashSet<operationalInformationByRequest>();
            this.riskInformationByRequest = new HashSet<riskInformationByRequest>();
        }
    
        public int rqt_id { get; set; }
        public Nullable<System.DateTime> rqt_registrationDate { get; set; }
        public Nullable<System.DateTime> rqt_firstVisitDate { get; set; }
        public Nullable<System.DateTime> rqt_lastVisitDate { get; set; }
        public Nullable<int> prb_id { get; set; }
        public Nullable<int> rqt_primaryState { get; set; }
        public Nullable<int> rqt_secondState { get; set; }
        public string cli_document { get; set; }
        public string usu_document { get; set; }
        public Nullable<bool> rqt_state { get; set; }
        public Nullable<int> cnt_id { get; set; }
        public string rqt_observation { get; set; }
        public Nullable<int> cnl_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operationalInformationByRequest> operationalInformationByRequest { get; set; }
        public virtual probability probability { get; set; }
        public virtual states states { get; set; }
        public virtual states states1 { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riskInformationByRequest> riskInformationByRequest { get; set; }
        public virtual Canal Canal { get; set; }
    }
}
