//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class riskInformationByRequest
    {
        public int ribr_id { get; set; }
        public Nullable<int> rqt_id { get; set; }
        public Nullable<System.DateTime> ribr_dateSubmissionAnalysis { get; set; }
        public Nullable<System.DateTime> ribr_dateResposeAnalysis { get; set; }
        public Nullable<long> ribr_ammountApproved { get; set; }
        public Nullable<int> sta_id { get; set; }
        public Nullable<bool> ribr_state { get; set; }
        public Nullable<System.DateTime> ribr_dateFiling { get; set; }
        public Nullable<System.DateTime> ribr_dateUpdateRow { get; set; }
        public string usu_document { get; set; }
        public Nullable<System.DateTime> ribr_dateApproved { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual states states { get; set; }
        public virtual users users { get; set; }
    }
}
