//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class states
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public states()
        {
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
            this.riskInformationByRequest = new HashSet<riskInformationByRequest>();
            this.PreRequest = new HashSet<PreRequest>();
        }
    
        public int sta_id { get; set; }
        public string sta_description { get; set; }
        public Nullable<int> sta_parentState { get; set; }
        public Nullable<bool> sta_state { get; set; }
        public Nullable<int> stGrp_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riskInformationByRequest> riskInformationByRequest { get; set; }
        public virtual stateGroup stateGroup { get; set; }
        public virtual states states1 { get; set; }
        public virtual states states2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest> PreRequest { get; set; }
    }
}
