//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.TemplateField = new HashSet<TemplateField>();
        }
    
        public int tmp_id { get; set; }
        public string tmp_prefix { get; set; }
        public string tmp_name { get; set; }
        public string tmp_description { get; set; }
        public string tmp_sp_to_execute { get; set; }
        public string tmp_separator { get; set; }
        public Nullable<System.DateTime> tmp_registration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateField> TemplateField { get; set; }
    }
}
