//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateField
    {
        public int tmpFl_id { get; set; }
        public int tmp_id { get; set; }
        public string tmpFl_name { get; set; }
        public string tmpFl_description { get; set; }
        public Nullable<int> tmpFl_position { get; set; }
        public string tmpFl_parameter_name { get; set; }
        public string tmpFl_parameterType { get; set; }
        public Nullable<System.DateTime> tmpFl_registration_date { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
