//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class userByRol
    {
        public int ubr_id { get; set; }
        public string usu_document { get; set; }
        public Nullable<int> rol_id { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual users users { get; set; }
    }
}
