//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.logins = new HashSet<logins>();
            this.operationalInformationByRequest = new HashSet<operationalInformationByRequest>();
            this.Request = new HashSet<Request>();
            this.riskInformationByRequest = new HashSet<riskInformationByRequest>();
            this.userByRol = new HashSet<userByRol>();
            this.PreClient = new HashSet<PreClient>();
            this.PreRequest = new HashSet<PreRequest>();
            this.PreRequest_Observation = new HashSet<PreRequest_Observation>();
        }
    
        public string usu_document { get; set; }
        public Nullable<int> kod_id { get; set; }
        public string usu_name { get; set; }
        public string usu_lastName { get; set; }
        public string usu_email { get; set; }
        public string usu_cellphone { get; set; }
        public string usu_adress { get; set; }
        public Nullable<int> cty_id { get; set; }
        public Nullable<int> jt_id { get; set; }
        public Nullable<int> rol_id { get; set; }
        public Nullable<bool> usu_state { get; set; }
        public Nullable<System.DateTime> usu_registerDate { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual jobTitle jobTitle { get; set; }
        public virtual kindOfDocument kindOfDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logins> logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operationalInformationByRequest> operationalInformationByRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riskInformationByRequest> riskInformationByRequest { get; set; }
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userByRol> userByRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreClient> PreClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest> PreRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreRequest_Observation> PreRequest_Observation { get; set; }
    }
}
